######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 28 17:07:33 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /usr/include/qwt-qt4/
unix:LIBS += -lqwt-qt4

# Input
HEADERS += plot.h
SOURCES += main.cpp plot.cpp

