.TH DINNERD 8 "14 Apr 2001" "Free Software" "User Manuals"
.SH NAME
dinnerd \- dinning hackers protocol daemon
.SH SYNOPSIS
dinnerd [\--nodaemon]

.SH DESCRIPTION
dinnerd is an implementation of the dinning hackers protocol,
which is loosely based on the Dinning Philosophers problem
proposed by Dijkstra and also on Steve Jackson's GURPS
role-playing system.

.SH "COMMAND-LINE OPTIONS"
.IP --nodaemon
runs in non-daemon mode, highly verbose (will report
every request and hit rolls performed by the server)

.SH BUGS
Anyone using this daemon on a regular basis should seek
psychiatric help immediatly.

.SH AUTHORS
dinnerd (and the Dinning Hackers protocol) was implemented
and created by Felipe Bergo <bergo@seul.org> as an example
for a tutorial.

.SH "SEE ALSO"
\fBhungryhacker\fR(1)
